analytics-ufcg/rcongresso

- DESCRIPTION
- R/qmr.R
- R/utils.R
- R/votacoes.R
_Work around_ sobre o problema de referências para as páginas seguintes.
> Pega todos os votos relacionados à uma votação

- .gitignore
- DESCRIPTION
- vignettes/quem-me-representa.Rmd
_Vignette_ sobre como utilizar as funções do pacote na construção do dataframe para o QMR.
> Adiciona vignettes

- R/pega_votacoes.R
- R/proposicoes.R
- R/qmr.R
Essas branches são praticamente idênticas, logo vou unificá-las a fim de evitar trabalho dobrado/duplicado.
> Unificação de branches semelhantes

- R/qmr-utils.R
- R/votacoes.R
As próximas mudanças serão feitas no _master_.  São necessárias mudanças na lógica de recebimento dos parâmetros para montagem do dataframe.
> Insere pequenas alterações

- DESCRIPTION
- tests/testthat/test_votacoes.R
> Resolve conflito tidyr

- R/proposicoes.R
- tests/testthat/test_proposicoes.R
> Trata IDs repetidos em fetch_tramitacao (fix #79)

- R/colunas_constants.R
- R/proposicoes.R
> Resolve bug de autor inexistente

- R/proposicoes.R
- tests/testthat/test_proposicoes.R
> 822 bug prop senado

- R/agenda.R
> Ajeita bug

- R/emendas.R
> Adiciona restrição

- R/agenda.R
A data vinha dia, mes e ano, mas a formatação tava ano, mes e dia
> Formata a data corretamente

- R/constants.R
- R/utils.R
> Corrige erro http 429

- DESCRIPTION
- tests/testthat/test_agenda.R
> Fix staged install issue

- .travis.yml
- DESCRIPTION
- R/agenda.R
- tests/testthat/test_agenda.R
> Adiciona a pauta das Reuniões

- R/utils.R
- tests/testthat/test_utils.R
> Evita que o rcongresso quebre caso venham novas colunas da api

- R/emendas.R
> Retira documentos que não são emendas

- R/emendas.R
- tests/testthat/test_emendas.R
Estava dando erro nos seguintes ids:
102721
--
111048
126049
> Corrige o bug ao baixar as emendas

- R/proposicoes.R
> Corrige bug que impedia de baixar a proposição do Senado com o id 138726

- R/emendas.R
> Ajeita as colunas

- R/proposicoes.R
> Ajeita nomes dos autores do Senado

- R/emendas.R
- R/proposicoes.R
- R/utils.R
- tests/testthat/test_agenda.R
- tests/testthat/test_emendas.R
- tests/testthat/test_utils.R
> Corrige bug emendas senado

- R/proposicoes.R
- tests/testthat/test_agenda.R
- Checar se os autores retornados por uma proposição estão duplicados ou não
> Remove duplicação no nome de autores de proposições

- R/colunas_constants.R
- R/senadores.R
- Lida com exceção nos casos onde os dados dos senadores não são retornados;
- Altera tipo de campo de dataframe da situação dos deputados.
> Trata exceções e altera tipo de campo em coluna

- R/tramitacoes.R
- Trata caso de tramitação do senado contendo apenas um informe legislativo;
- Conserta formatação do arquivo tramitacoes.R
> Fix tramitacao

- R/proposicoes.R
- Checa se coluna existe antes de operação por ordenação
- Exemplo de proposição que apresentava problemas: PL 3267/2019
> Checa se coluna existe antes de operação por ordenação

- R/config/regex_camara.json
- R/requerimentos.R
- Adiciona novos regex para captura de eventos na tramitação de requerimentos
> Adiciona regex com eventos de requerimento

- R/agenda.R
- Adapta função que recupera agenda do senado ao novo formato do endpoint da API do senado.
> Corrige função que recupera agenda do senado

- DESCRIPTION
- R/colunas_constants.R
- R/constants.R
- R/proposicoes.R
- Altera data da situação da proposição no Senado quando apenas a data de tramitação no local atual está disponível
> Altera data da situação da proposição no Senado 

- R/agenda.R
- Conserta fetcher de agenda no senado
Evita erro quando os dados da agenda na semana "2021-06-07" até "2021-06-11" são recuperados.
> Conserta fetcher de agenda no senado
